### ISSUE TITLE
i get an error on npm start

### ISSUE THREAD

**Issue by justinchristensen66** [StephenGrider/ReduxSimpleStarter#116]
I was video #47 when this happened, but it happened on a fresh start of a git clone as well.  This was working fine yesterday and then today on npm start- 
ustins-MacBook-Pro-2:ReduxSimpleStarter justinchristensen66$ npm start

> redux-simple-starter@1.0.0 start /Users/justinchristensen66/sandbox/React/foo/udemy/ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/justinchristensen66/.nvm/v6.10.3/bin/node" "/Users/justinchristensen66/.nvm/v6.10.3/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-simple-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/justinchristensen66/sandbox/React/foo/udemy/ReduxSimpleStarter/npm-debug.log

I wonder what I did, because like I said it was working yesterday, and I tried starting from a clean slate new git clone and got the same error.  Any help would be much appreciated!

**Comment by justinchristensen66** [comment]
sorry I already had something running on port 8080!?!? Thats why it failed/1  My bad !
