### ISSUE TITLE
npm start - ReduxSimpleStarter

### ISSUE THREAD

**Issue by sailedvc** [StephenGrider/ReduxSimpleStarter#118]
**I have 4.6.1 node version.
I execute npm install and then npm start and the following error is displayed:**

> redux-simple-starter@1.0.0 start C:\wamp64\www\react\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by osolano** [comment]
Same here I get the same error.

**Comment by michaelunltd** [comment]
same error for me.

**Comment by nhtua** [comment]
It is conflicted PC open port. Please choose another port to start Redux Simple Starter. Just update a bit in `webpack.config.js`: 
`devServer: {
    historyApiFallback: true,
    contentBase: './',
    port: 3000 // <--- Add this line and choose your own port number
  }`

then run `npm start` again

**Comment by cptdesro** [comment]
You are probably killing your process with CTRL-Z, try using CTRL-C. It will send a SIGINT that will end your program the right way, unbinding your process from any ports it is listening on.

**Comment by Marbocatcat** [comment]
Just choose a different port in webpack.config.js

**Comment by bsai** [comment]
yeah..started server

**Comment by raviji** [comment]
Yes it is port issue, thank you guys

**Comment by sraakesh95github** [comment]
> It is a conflicted port. Please choose another port to start Redux Simple Starter. Just update a bit in `webpack.config.js`:
> 
> ```
> devServer: {
>     historyApiFallback: true,
>     contentBase: './',
>     port: 3000 // <--- Add this line and choose your own port number
>   }
> ```
> 
> then run `npm start` again

Cool it worked out. Thanks

**Comment by raviji** [comment]
You can stop your IIS server from windows machines and its default port is :8080 then your problem solved.

**Comment by HienDoanTan** [comment]
> It is a conflicted port. Please choose another port to start Redux Simple Starter. Just update a bit in `webpack.config.js`:
> 
> ```
> devServer: {
>     historyApiFallback: true,
>     contentBase: './',
>     port: 3000 // <--- Add this line and choose your own port number
>   }
> ```
> 
> then run `npm start` again

thank you. that cool!
