### ISSUE TITLE
npm start throw an error 

### ISSUE THREAD

**Issue by Mian007** [StephenGrider/ReduxSimpleStarter#174]
C:\Users\Mian\Desktop\Order\ReactCourse\ReduxSimpleStarter>npm start

> redux-simple-starter@1.0.0 start C:\Users\Mian\Desktop\Order\ReactCourse\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\Mian\Desktop\Order\ReactCourse\ReduxSimpleStarter\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mian\AppData\Roaming\npm-cache\_logs\2017-11-01T00_54_15_591Z-debug.log

i tried all things and install webpack-dev-server but same error

**Comment by JonZso** [comment]
Have you solved it yet?
