### ISSUE TITLE
Can't launch npm start

### ISSUE THREAD

**Issue by toms5617** [StephenGrider/ReduxSimpleStarter#175]
Hi, I can't manage to get npm start work- this is the error text provided in console after running npm start.

> ReduxSimpleStarter-master@1.0.0 start C:\xampp\htdocs\udemy\react-redux\ReduxSimpleStarter-master
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\xampp\htdocs\udemy\react-redux\ReduxSimpleStarter-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)

at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ReduxSimpleStarter-master@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1

npm ERR!
npm ERR! Failed at the ReduxSimpleStarter-master@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReduxSimpleStarter-master package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ReduxSimpleStarter-master
npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls ReduxSimpleStarter-master
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\udemy\react-redux\ReduxSimpleStarter-master\npm-debug.log

Thanks

**Comment by andreidobrinski** [comment]
I had the same issue. Try this:
- navigate to your project file in the terminal
- run `npm install`
- run `npm start`

Installing the dependencies first worked for me. Hope that helps!

**Comment by zijld** [comment]
Something to do with High Sierra I think because brew update didn't work either
I did reinstall my Homebrew and it worked.

Uninstall:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

Install:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
