### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by ladygarnet00** [StephenGrider/ReduxSimpleStarter#190]
> npm ERR! Darwin 17.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-simple-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

Hi! im Udemy Student (btw thanks for the course, its been great), and i need install your react boilerplate. Plzz update the dependencies.
Thanks for all !

**Comment by maniinus** [comment]
unable to start the server

0 info it worked if it ends with ok
1 verbose cli [ '/Users/ArunHari/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/Users/ArunHari/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-simple-starter@1.0.0~prestart: redux-simple-starter@1.0.0
6 info lifecycle redux-simple-starter@1.0.0~start: redux-simple-starter@1.0.0
7 verbose lifecycle redux-simple-starter@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle redux-simple-starter@1.0.0~start: PATH: /Users/ArunHari/.nvm/versions/node/v8.9.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/ArunHari/Desktop/ReduxSimpleStarter/node_modules/.bin:/Users/ArunHari/.nvm/versions/node/v8.9.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle redux-simple-starter@1.0.0~start: CWD: /Users/ArunHari/Desktop/ReduxSimpleStarter
10 silly lifecycle redux-simple-starter@1.0.0~start: Args: [ '-c',
10 silly lifecycle   'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js' ]
11 silly lifecycle redux-simple-starter@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle redux-simple-starter@1.0.0~start: Failed to exec start script
13 verbose stack Error: redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/ArunHari/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/ArunHari/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid redux-simple-starter@1.0.0
15 verbose cwd /Users/ArunHari/Desktop/ReduxSimpleStarter
16 verbose Darwin 17.2.0
17 verbose argv "/Users/ArunHari/.nvm/versions/node/v8.9.1/bin/node" "/Users/ArunHari/.nvm/versions/node/v8.9.1/bin/npm" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
22 error Exit status 1
23 error Failed at the redux-simple-starter@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by maniinus** [comment]
follow this incase your PORT is in use and you get this error 
Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)


https://github.com/StephenGrider/ReduxSimpleStarter/issues/23

**Comment by Benikens** [comment]
I have the same issue as you and it seems a couple other posters here to, has anyone found a way to get this to work?

**Comment by alarez** [comment]
Here is a possible solution to that https://github.com/StephenGrider/ReduxSimpleStarter/issues/168

**Comment by Benikens** [comment]
I tried changing the port number I'm still having the same problem

**Comment by Benikens** [comment]
Hey if anyone is stuck on this Stephen sorted me out. What was happening was apparently node wasn't installed right, so he got me to download it from here https://nodejs.org/en/download/ when I extracted it and tried to run not from the files it prompted me to: sudo apt-get install nodejs-legacy after which I could start my the project fine.

**Comment by Teskin** [comment]
Benikens, what does it even mean? 

Do you have a Mac and you installed it through command line? And what about Windows' owners?

Please, add some clarifications.

Thank you.

**Comment by Benikens** [comment]
I use Ubuntu. I installed from command line originally then downloaded the install-able files for node.js manually from that link. I tried to install from those files and it prompted me to type the above command in cli, which is install nodejs-legacy and then after that it worked right. Does that make sense?

**Comment by vinay72** [comment]
You must try installing the latest version of npm and node.js installed in your terminal.
