### ISSUE TITLE
React boiler plate project cloning error: SOLUTION

### ISSUE THREAD

**Issue by NAAG1999** [StephenGrider/ReduxSimpleStarter#218]
npm start

> redux-simple-starter@1.0.0 start /home/nilesh/Desktop/Work/React files/ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

sh: 1: node: not found

npm ERR! Linux 4.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-simple-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

For all guys facing the same error  
Do the following:
1) Go to your terminal and install node ( not node js cause you have already installed node js and npm)

This could be done by writing:

**sudo apt get install nodejs-legacy** 

in your terminal and after the package is installed

go to your project file folder i.e ReduxSimpleStarter and start the server by writing following command

**npm start**

Note : Non mac users can ignore the architecture error that my come during (npm install )

Kindly let me know in the comments, if you guys face any further problem

**Comment by mohdmunsif** [comment]
what about those on windows?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-simple-starter@1.0.0~prestart: redux-simple-starter@1.0.0
6 info lifecycle redux-simple-starter@1.0.0~start: redux-simple-starter@1.0.0
7 verbose lifecycle redux-simple-starter@1.0.0~start: unsafe-perm in lifecycle true

9 verbose lifecycle redux-simple-starter@1.0.0~start: CWD: C:\wamp\www\ReduxSimpleStarter
10 silly lifecycle redux-simple-starter@1.0.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js' ]
11 silly lifecycle redux-simple-starter@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle redux-simple-starter@1.0.0~start: Failed to exec start script
13 verbose stack Error: redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid redux-simple-starter@1.0.0
15 verbose cwd C:\wamp\www\ReduxSimpleStarter
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
22 error Exit status 1
23 error Failed at the redux-simple-starter@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by toddnagel** [comment]
ok, after an hour or so, I was able to fix this by starting over ( alot of fixes for this issues ), then do a fresh npm install, and change in package-json the "scripts" "start" does not need the 'node and dir to webpack-dev-server', instead make it this:

"start": "webpack-dev-server"

and that's all I did to get it to work, on windows machine..of course took over an hour to try all the fixes..

**Comment by clawsn** [comment]
If anyone is having more issues with this try deleting the node_modules folder. Then, run `npm install`.  After that's done downloading run `npm cache clean --force` and `npm run dev`.
