### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by marcusdetry** [StephenGrider/ReduxSimpleStarter#219]
I keep getting a prompt that permission is denied when trying to clone the repository.  Can anyone help?  Thanks!

me:~ mdetry$ git clone git@github.com:StephenGrider/ReduxSimpleStarter.git
Cloning into 'ReduxSimpleStarter'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by yangalav** [comment]
did you try doing ```git clone https://github.com/StephenGrider/ReduxSimpleStarter.git```

**Comment by diamondcoder** [comment]
This is the error I get when I run npm start

C:\Users\idawebqueen\Desktop\React\ReduxSimpleStarter>npm start

> redux-simple-starter@1.0.0 start C:\Users\idawebqueen\Desktop\React\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\idawebqueen\AppData\Roaming\npm-cache\_logs\2018-04-09T21_26_47_054Z-debug.log

**Comment by marcusdetry** [comment]
@yangalav I did but never changed <new directory name> with the directory I wanted it to clone into.  It works now.  Thanks for the help!
