### ISSUE TITLE
npm start fails (webpack-dev-server issue ?)

### ISSUE THREAD

**Issue by eytansankin** [StephenGrider/ReduxSimpleStarter#22]
That's the error i'm getting. Any idea how to get past this ?
![image](https://cloud.githubusercontent.com/assets/11695483/14495580/c4363cba-0198-11e6-8a75-596007d10af7.png)

**Comment by eytansankin** [comment]
Solved : 
sudo apt-get install nodejs-legacy

**Comment by sedatiko** [comment]
Under Windows 7 with node and npm up to date, I get the following error when running npm start. Anyone got around this issue?

c:\Projects\ReduxSimpleStarter>npm start

> redux-simple-starter@1.0.0 start c:\Projects\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1217:19)
    at listen (net.js:1266:10)
    at net.js:1375:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-s
erver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-serv
er/bin/webpack-dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-simple-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Projects\ReduxSimpleStarter\npm-debug.log

**Comment by StephenGrider** [comment]
Awesome, glad you found the solution, going to leave this issue up for others

**Comment by terhubungdev** [comment]
I think I got another issue

```
> redux-simple-starter@1.0.0 start C:\laragon\www\react\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

/
module.js:340
    throw err;
          ^
Error: Cannot find module 'accepts'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\laragon\www\react\ReduxSimpleStarter\node_modules\webpack-dev-server\node_modules\compress
ion\index.js:17:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
-
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script.
npm ERR! This is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "start"
npm ERR! cwd C:\laragon\www\react\ReduxSimpleStarter
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\laragon\www\react\ReduxSimpleStarter\npm-debug.log
npm ERR! not ok code 0
```

I'm on windows 10 and I've tried using node-v0.10.29-x64 and node-v4.4.5-x64

**Comment by StephenGrider** [comment]
@terhubungdev rerun 'npm install'

**Comment by lahong** [comment]
the problem might be that your port 8080 is being used by another service
you can use port forward.com to see if thats the case
if yes
try and then use a different port

**Comment by sagargajera** [comment]
Try to put "module.exports = config;" at the end of webpack.config.js file. That might solve your problem

**Comment by cvasit** [comment]
Hello Friends
I am getting this error when I am trying to execute npm start on ReduxSimpleStarter.Appreciate your help. I did verify that port 80 is not in use.  I am using windows 7 home edition.
Regards
cvas

$ npm start

> redux-simple-starter@1.0.0 start C:\Working\Examples\ReactExamples\UdemyAdvancedCourse\ClientSideAuthentication
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-simple-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Working\Examples\ReactExamples\UdemyAdvancedCourse\ClientSideAuthentication\npm-debug.log

**Comment by akshaybhoendie** [comment]
just try port 3000

**Comment by Teskin** [comment]
I am experiencing a very similar issue that I am struggling on resolving it:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-simple-starter@1.0.0~prestart: redux-simple-starter@1.0.0
6 info lifecycle redux-simple-starter@1.0.0~start: redux-simple-starter@1.0.0
7 verbose lifecycle redux-simple-starter@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle redux-simple-starter@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\daa3\React\blog\ReduxSimpleStarter-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\daa3\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Heroku\bin;C:\Users\daa3\AppData\Roaming\npm;C:\Users\daa3\AppData\Local\.meteor;C:\Users\daa3\AppData\Local\Microsoft\WindowsApps;C:\Users\daa3\AppData\Local\atom\bin;C:\Users\daa3\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle redux-simple-starter@1.0.0~start: CWD: C:\Users\daa3\React\blog\ReduxSimpleStarter-master
10 silly lifecycle redux-simple-starter@1.0.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js' ]
11 silly lifecycle redux-simple-starter@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle redux-simple-starter@1.0.0~start: Failed to exec start script
13 verbose stack Error: redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid redux-simple-starter@1.0.0
15 verbose cwd C:\Users\daa3\React\blog\ReduxSimpleStarter-master
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
22 error Exit status 1
23 error Failed at the redux-simple-starter@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Teskin** [comment]
I am experience something similar that I cannot resolve:
![issue](https://user-images.githubusercontent.com/20303536/35159800-aacc5cd2-fd3b-11e7-841a-ed765ede3dac.png)
