### ISSUE TITLE
Error with "npm start"

### ISSUE THREAD

**Issue by Avchhikara** [StephenGrider/ReduxSimpleStarter#276]
Sir, I am getting the error shown in the picture below:
![react error](https://user-images.githubusercontent.com/30333795/46915947-16a7a480-cfd1-11e8-97c5-36fd7cf16dc9.PNG)

**Comment by DMIScottNoring** [comment]
C:\working\ReduxSimpleStarter>npm start

> redux-simple-starter@1.0.0 start C:\working\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1510:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:72:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script.

**Comment by DMIScottNoring** [comment]
I am getting my money back for the course due to this issue.

**Comment by DMIScottNoring** [comment]
I resolved it by changing the port in the webpack.config.js. Also make sure you open your terminal as admin.

devServer: {
      port: 3000, //Added this
    historyApiFallback: true,
    contentBase: './',
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
