### ISSUE TITLE
npm start problem

### ISSUE THREAD

**Issue by Dueldrawer8** [StephenGrider/ReduxSimpleStarter#66]
also have this problem whenever i enter in npm start

> redux-simple-starter@1.0.0 start C:\Users\Randy\ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! This is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Randy\ReduxSimpleStarter\npm-debug.log

**Comment by cielmik** [comment]
It means the port is in use (The prev npm start didn't close correctly or something), you have to kill the process. I think a simple restart did the job in windows for me, but for mac or linux you can simply :

ps aux | grep node
kill <process id>

**Comment by liovincis** [comment]
I am still having issues even with a restart in windows, am I missing something here? 

> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'errno'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (...\ReduxSimpleStarter\node_modules\webpack-dev-server\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:7:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! This is most likely a problem with the redux-simple-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-simple-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls redux-simple-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ...\ReduxSimpleStarter\npm-debug.log

**Comment by getstack** [comment]
She doesn"t create any problem with npm start its fine

**Comment by sahilsharmafrank** [comment]
As @cielmik  said port 8080 is used its not necessary that some node application is using it try closing skype or any application that uses port 8080 will fix the problemo.

**Comment by nickolaos77** [comment]
I have the same problem and @sahilsharmafrank 's solution didn't help me

**Comment by J-Yash** [comment]
Replace <node> with <nodejs> in package.json file(line 8). Worked for me(Ubuntu 16).
