### ISSUE TITLE
npm install and start issues

### ISSUE THREAD

**Issue by Devvl77** [StephenGrider/ReduxSimpleStarter#87]
I cloned your repositories and i got those warning

npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

and when i tried npm start i got those : 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-simple-starter@1.0.0~prestart: redux-simple-starter@1.0.0
6 silly lifecycle redux-simple-starter@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle redux-simple-starter@1.0.0~start: redux-simple-starter@1.0.0
8 verbose lifecycle redux-simple-starter@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle redux-simple-starter@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\mycomputer\ReduxSimpleStarter\node_modules\.bin;C:\Users\mycomputer\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\mycomputer\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Common Files\Acronis\SnapAPI;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\mycomputer\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle redux-simple-starter@1.0.0~start: CWD: C:\Users\mycomputer\ReduxSimpleStarter
11 silly lifecycle redux-simple-starter@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js' ]
12 silly lifecycle redux-simple-starter@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle redux-simple-starter@1.0.0~start: Failed to exec start script
14 verbose stack Error: redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid redux-simple-starter@1.0.0
16 verbose cwd C:\Users\mycomputer\ReduxSimpleStarter
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
22 error Exit status 1
23 error Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-simple-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs redux-simple-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls redux-simple-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Im having XAMPP working on port 82 and im using skype

**Comment by Devvl77** [comment]
I installed linux and its working
