### ISSUE TITLE
Cannot run "test" or "test:watch"

### ISSUE THREAD

**Issue by prakashgbid** [StephenGrider/ReduxSimpleStarter#88]
When I try to run either of the following commands, 

$ npm run test
 OR
$ npm run test:watch

I get error. Below is the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@3.8.6
3 info using node@v7.0.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle redux-simple-starter@1.0.0~pretest: redux-simple-starter@1.0.0
6 silly lifecycle redux-simple-starter@1.0.0~pretest: no script for pretest, continuing
7 info lifecycle redux-simple-starter@1.0.0~test: redux-simple-starter@1.0.0
8 verbose lifecycle redux-simple-starter@1.0.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle redux-simple-starter@1.0.0~test: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ptiw10/Desktop/practice/react/react-unit-testing/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle redux-simple-starter@1.0.0~test: CWD: /Users/ptiw10/Desktop/practice/react/react-unit-testing
11 silly lifecycle redux-simple-starter@1.0.0~test: Args: [ '-c',
11 silly lifecycle   'mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test' ]
12 silly lifecycle redux-simple-starter@1.0.0~test: Returned: code: 1  signal: null
13 info lifecycle redux-simple-starter@1.0.0~test: Failed to exec test script
14 verbose stack Error: redux-simple-starter@1.0.0 test: `mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid redux-simple-starter@1.0.0
16 verbose cwd /Users/ptiw10/Desktop/practice/react/react-unit-testing
17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
19 error node v7.0.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error redux-simple-starter@1.0.0 test: `mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test`
22 error Exit status 1
23 error Failed at the redux-simple-starter@1.0.0 test script 'mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-simple-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs redux-simple-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls redux-simple-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by andrit** [comment]
It seems I have the same issue.  What version of Node and npm are you running?

**Comment by mikeerickson** [comment]
@andrit the version information as at the top of debug.log

**Comment by andrit** [comment]
@mikeerickson right, thanks.  Have you had this issue at all?

**Comment by mikeerickson** [comment]
@andrit no, it works fine for me. I will have a look at this closer in the morning when back In computer.  I am sure it will be a straightforward fix

**Comment by andrit** [comment]
@mikeerickson thatd be great. 
I also found this in my terminal:

SyntaxError: /Users/UserName/Directory/react-redux-starter/test/test_helper.js: Unexpected token (21:4)
  19 | function renderComponent(ComponentClass, props = {}, state = {}) {
  20 |   const componentInstance =  TestUtils.renderIntoDocument(
> 21 |     <Provider store={createStore(reducers, state)}>
     |     ^
  22 |       <ComponentClass {...props} />
  23 |     </Provider>
  24 |   );

**Comment by prakashgbid** [comment]
@andrit : How did you get the repo ? I mean did you use "Download Zip" or "Open in Desktop" ?
I was having this problem when I downloaded the zip. But then, it worked fine when I used the other option, which is "Open in Desktop". I hope this will fix it. At least it worked for me. Not sure how and why though !!

**Comment by andrit** [comment]
@prakashgbid Actually I used git clone in my terminal.  I'll try it the other way though.  Thanks.

**Comment by andrit** [comment]
@prakashgbid & @mikeerickson 
This fixed it for me:
 I didnt have a .babelrc file for some reason.  
contents must match whats found here: https://github.com/StephenGrider/AdvancedReduxCode/blob/master/testing/.babelrc
